---
- include: preflight.yml

- include: install.yml

- include: configure.yml

- name: ensure alertmanager service is started and enabled
  systemd:
    name: alertmanager
    state: started
    enabled: yes
