---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted

- name: reload alertmanager
  service:
    name: alertmanager
    state: reloaded
